### ISSUE TITLE
Transfer repository to alchemyrpg github org

### ISSUE THREAD

**Issue by thatbudakguy** [alchemyrpg/ddb2alchemy#16]
This is probably best for the longevity of the project, especially if I can't maintain it anymore.

It looks like I don't have permissions to do this since I'm not a member of the org. I think there are two ways to fix that:
1. make me a member of the org, maybe on a special team (for community devs?) or with special permissions
2. grant someone who _is_ a member of the org admin on this repo and have them transfer it (I think this would work?)

This will change the github URL, so probably needs to happen at the same time as a change within Alchemy to point to the new location.

**Comment by ioveracker** [comment]
If you're cool with this, that sounds fine to me! Let's go with option 2:

- make me an admin on this repo and I can start the transfer
- once it has transferred over, I'll invite you as a collaborator on the repository at its new location (if this is even needed, you might inherit it anyway)

**Comment by thatbudakguy** [comment]
I guess I was wrong...it seems from [these docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository#collaborator-access-for-a-repository-owned-by-a-personal-account) that there aren't any permissions on personal repos other than "collaborator", and collaborators aren't allowed to transfer repos. Which I guess makes some sense.

**Comment by thatbudakguy** [comment]
Maybe I could still transfer it to alchemyrpg if I'm a "collaborator" on that org, rather than a member?

**Comment by ioveracker** [comment]
Ah, in that case, you could transfer ownership to me and then I can transfer to the alchemyrpg org, and then make sure you're a collaborator there. 😁

**Comment by thatbudakguy** [comment]
transfer complete!

**Comment by ioveracker** [comment]
Woot! It has successfully been transferred into the org and you're still a collaborator, so I think we're all set now!

Thanks! 🎉

**Comment by ioveracker** [comment]
You _might_ need to update your remote url now. For me, since I use SSH for GitHub, the command was:
```
git remote set-url origin git@github.com:alchemyrpg/ddb2alchemy.git
```
