### ISSUE TITLE
Error creating certain spells with components

### ISSUE THREAD

**Issue by ioveracker** [alchemyrpg/ddb2alchemy#24]
## What happened?
Converting character from D&D Beyond to Alchemy JSON throws an error.

```
Cannot read properties of undefined (reading '0')
```

Stacktrace from Alchemy internal error reporting:
![image](https://user-images.githubusercontent.com/1653961/213941966-13d8adc3-39df-4e51-aed7-abe3867e2bd5.png)

## D&D Beyond Character Link
https://ddb.ac/characters/64766909/RRCKTv

**Comment by thatbudakguy** [comment]
The spell in question seems to be [Jim's Glowing Coin, from _Acquisitions Incorporated_](http://dnd5e.wikidot.com/spell:jims-glowing-coin). DDB lists it as having:
```json
            "components": [
              2,
              3,
              4
            ],
```
2 and 3 are somatic and material...not sure how to read component type 4 here. "custom"? "consumes item"? at any rate I don't think Alchemy has any way of representing this, so maybe we should simply ignore it.
